# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
require "vine"

#
# access.rb
#

# ---- original file header ----
#
# @summary
#   
#    Uses Vine gem to deep access hash/array keys
#
#
Puppet::Functions.create_function(:'access') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    

    unless (args.length == 2) || (args.length == 3)
      raise Puppet::ParseError, ("access(): wrong number of arguments (#{args.length}; must be 2 or 3)")
    end

    container = args[0]

    if (!container.is_a?(Hash)) && (!container.is_a?(Array))
      raise Puppet::ParseError, ("access(): expecting first parameter as Array or Hash, #{container.class} given")
    end

    keys = args[1]

    default = (args[2].nil?) ? nil : args[2]

    if container.access(keys).class == NilClass
      return default
    end

    return container.access(keys)

  
  end
end
